/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplo_proyecto;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author federico
 */
public class VentanaInvestigador extends javax.swing.JFrame {

    /**
     * Creates new form Investigadores
     */
    
    DefaultTableModel dtablemodel = new DefaultTableModel();
    DefaultTableModel dtablemodel2 = new DefaultTableModel(); //Muestras
    
    //Constructor de ventana
    public VentanaInvestigador() {
        initComponents();
        
        //Llenar columnas
        String []columnas = {"Codigo", "Nombre", "Experimentos"};
        for(String columna: columnas) {
            dtablemodel.addColumn(columna);
        }
        
        //Llenar filas
        for(Investigador inv: Ejemplo_Proyecto.lista_investigador) {
            Object []fila = {inv.codigo, inv.nombre, inv.cantidad};
            dtablemodel.addRow(fila);
        }
        
        tablaInvestigador.setModel(dtablemodel);
        
        String []columnas2 = {"Codigo", "Descripcion"};
        for (String columna: columnas2) {
            dtablemodel2.addColumn(columna);
        }
        for (Muestras mu: Ejemplo_Proyecto.lista_muestras) {
            Object []fila = {mu.codigo, mu.descripcion};
            dtablemodel2.addRow(fila);
        }
        
        tablaMuestras.setModel(dtablemodel2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInvestigador = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMuestras = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaInvestigador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaInvestigador);

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cargar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("Serializar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Investigador", jPanel1);

        jButton4.setText("Crear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cargar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tablaMuestras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaMuestras);

        jButton7.setText("Ver");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jTabbedPane1.addTab("Muestras", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AgregarInvestigador investigador = new AgregarInvestigador();
        investigador.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Borrar filas
        dtablemodel.setRowCount(0);
        //Actualizar tabla
        for (Investigador inv: Ejemplo_Proyecto.lista_investigador) {
            Object []fila = {inv.codigo, inv.nombre, inv.cantidad};
            dtablemodel.addRow(fila);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            //File archivo = null;
            FileReader fileR = null;
            BufferedReader bufferedReader = null;
            
            //Mostrar ventana de dialogo para seleccionar archivo csv
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.showOpenDialog(null);
            File archivo = fileChooser.getSelectedFile();
            fileR = new FileReader(archivo);
            bufferedReader = new BufferedReader(fileR);
            
            String linea;
            boolean omitirEncabezado = true;
            
            //Leer archivo linea por linea
            while ((linea = bufferedReader.readLine()) != null) {
                //Omitir encabezado
                if (omitirEncabezado == true) {
                    omitirEncabezado = false;
                    continue;
                }
                //I1,User,2,123
                String arreglo[] = linea.split(",");
                //Codigo = arreglo[0]
                //Nombre = arreglo[1]
                //Cantidad = arreglo[2]
                //Password = arreglo[3]
                int cantidad = Integer.parseInt(arreglo[2]); //Convertir cadena a entero
                //Se crea objeto investigador
                Investigador inv = new Investigador(arreglo[0], arreglo[1], cantidad, arreglo[3]);
                //Almacenar objeto en lista
                Ejemplo_Proyecto.lista_investigador.add(inv);
            }
        } catch(Exception e) {
            
        }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CrearMuestra muestra = new CrearMuestra();
        muestra.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        try {
            File archivo = null;
            FileReader fileR = null;
            BufferedReader bufferedReader = null;
            
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.showOpenDialog(null);
            archivo = fileChooser.getSelectedFile();
            fileR = new FileReader(archivo);
            bufferedReader = new BufferedReader(fileR);
            
            String linea;
            boolean omitirEncabezado = true;
            
            while ((linea = bufferedReader.readLine()) != null) {
                if (omitirEncabezado == true) {
                    omitirEncabezado = false;
                    continue;
                }
                /*
                codigo, descripcion,patron
                M1,Muestra1,1;2;3;4
                */
                String arreglo[] = linea.split(",");
                //Codigo = arreglo[0]
                //Descripcion = arreglo[1]
                //Patron = arreglo[2]
                String arregloPatron[] = arreglo[2].split(";");
                
                //Formula para obtener tamaño de filas y columnas
                //len(filas o columnas) = raiz(len(arreglo separado por punto y coma))
                int longitud = (int) Math.sqrt(arregloPatron.length);
                //Crear matriz
                int matriz[][] = new int[longitud][longitud];
                int contador = 0;
                
                for (int i = 0; i < longitud; i++) {
                    for (int j = 0; j < longitud; j++) {
                        matriz[i][j] = Integer.parseInt(arregloPatron[contador]);
                        contador++;
                    }
                }
                Muestras muestra = new Muestras(arreglo[0], arreglo[1], "Ingreso", matriz);
                Ejemplo_Proyecto.lista_muestras.add(muestra);
            }
            
        } catch(Exception e) {
            
        } 
    }//GEN-LAST:event_jButton5ActionPerformed
 
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        EliminarInvestigador eliminar = new EliminarInvestigador();
        eliminar.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int columna = 0;
        int fila = tablaMuestras.getSelectedRow(); //posicion fila
        String codigo = tablaMuestras.getModel().getValueAt(fila, columna).toString();
        reporteHtml(codigo);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Ejemplo_Proyecto.serializar();  //Llamada de metodo estatico
    }//GEN-LAST:event_jButton8ActionPerformed

    public Muestras buscarMuestra(String codigo) {
        for (Muestras mu: Ejemplo_Proyecto.lista_muestras) {
            if (mu.codigo.equals(codigo)) {
                return mu;  //Retorna el objeto muestra
            }
        }
        return null;
    }
    
    public void reporteHtml(String codigo) {
        
        try {
            String ruta = codigo + ".html";
            File archivo = new File(ruta);
            
            if (archivo.exists() == false) { //archivo no existe
                archivo.createNewFile();
            }
            FileWriter fileWriter = new FileWriter(archivo);
            BufferedWriter buffer = new BufferedWriter(fileWriter);
            
            String html = "<html>"
                    + "<body>"
                    + "<table border='1'>";
            //For para recorrrer filas
            for (int i = 0; i < buscarMuestra(codigo).matriz.length; i++) {
                html += "<tr>";
                //For para recorrer columnas
                for (int j = 0; j < buscarMuestra(codigo).matriz[i].length; j++) {
                    html += "<td>" + buscarMuestra(codigo).matriz[i][j] + "</td>";
                }
                html += "</tr>";
            }
            
            html += "</tbody>"
                    + "</body>"
                    + "</html>";
            
            buffer.write(html);
            buffer.close();
            fileWriter.close();
            
        } catch (Exception e) {
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInvestigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInvestigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInvestigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInvestigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInvestigador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaInvestigador;
    private javax.swing.JTable tablaMuestras;
    // End of variables declaration//GEN-END:variables
}
